name: Deploying_Web_App
on:
  push:
    branches:
      - dev
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Web App Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfiles/Dockerfile.web
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/codearena-web-dev:latest
            ${{ secrets.DOCKER_USERNAME }}/codearena-web-dev:${{ github.sha }}


      - name: Deploy to dev aws_server_ec2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST_DEV }}
          username: ${{ secrets.SERVER_USER_DEV }}
          key: ${{ secrets.SERVER_SSH_KEY_DEV }}
          script: |
            sudo docker stop codearena-web-dev || true
            sudo docker rm codearena-web-dev || true

            sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/codearena-web-dev:latest || true
            sudo docker image prune -af

            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/codearena-web-dev:latest

            sudo docker run -d --name codearena-web-dev -p 3000:3000 -e DATABASE_URL="${{ secrets.DATABASE_URL_DEV }}" -e JUDGE0_URI="${{ secrets.JUDGE0_URI_DEV }}" ${{ secrets.DOCKER_USERNAME }}/codearena-web-dev:latest
            